# yaml-language-server: $schema=https://json.schemastore.org/netlify.json

backend:
  name: github
  repo: 'wasmcloud/wasmcloud.com'
  branch: main
  commit_messages:
    create: 'chore({{collection}}): Create {{slug}}'
    update: 'chore({{collection}}): Update {{slug}}'
    delete: 'chore({{collection}}): Delete {{slug}}'
    uploadMedia: 'chore(media): Upload {{path}}'
    deleteMedia: 'chore(media): Delete {{path}}'
  
public_folder: static
media_folder: static/uploads
display_url: 'https://wasmcloud.com'
logo_url: '/static/logo/wasmcloud_green.svg'
publish_mode: editorial_workflow

collections:
  - name: 'community'
    label: 'Community Meetings'
    folder: '/community'
    extension: 'mdx'
    format: 'docusaurus'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Tags', name: 'tags', widget: 'list', field: {label: 'Tag', name: 'tag', widget: 'string'}}
      - {label: 'Featured Image', name: 'thumbnail', widget: 'image'}
